services:
  web:
    build: .
    container_name: my-web
    ports:
      - "${WEB_PORT:-8080}:80"
    environment:
      - SERVICE_NAME=web
      - NGINX_ENTRYPOINT_QUIET_LOGS=${NGINX_ENTRYPOINT_QUIET_LOGS}
    depends_on:
      - cache

  cache:
    image: redis:alpine
    container_name: my-cache
